### PR TITLE
📝 Write initial README.md

### PR DESCRIPTION
**Pull request by FateUnix29**
Add the initial README!

### CODE REVIEW

**Comment by FateUnix29** [comment]
I did forget to add a 'special thanks to' sub-section in the 'Credits' section.

**Comment by FateUnix29** [comment]
I fixed it.

**Comment by AbsolutelyNotConspicuous** [comment]
I'll add a `developing.md` file later. Gotta get perru to send over some stuff for logos.

**Comment by FateUnix29** [comment]
K

**Pull request merged**
